name: Build OpenWRT in Github owned Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
        #sudo yum groupinstall "Development Tools" -y
        #sudo yum install cmake ncurses-devel zlib-devel gcc gcc-c++ patch unzip bzip2 gettext perl-Data-Dumper rsync -y
        #sudo yum install git subversion gawk libtool zlib-devel gcc make ncurses-devel patch wget bzip2 flex bison gperf python3 python3-pip python3-setuptools -y
        #sudo yum install glibc-devel glibc-static texinfo expat-devel gettext-devel openssl-devel -y
        #sudo yum install perl perl-CPAN -y
        #sudo cpan IPC::Cmd
        #yes

    - name: Cache OpenWRT dl folder
      uses: actions/cache@v3
      with:
        path: $GITHUB_WORKSPACE/dl
        key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('$GITHUB_WORKSPACE/feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-dl-

    - name: Cache OpenWRT build_dir
      uses: actions/cache@v3
      with:
        path: $GITHUB_WORKSPACE/build_dir
        key: ${{ runner.os }}-openwrt-build-${{ hashFiles('$GITHUB_WORKSPACE/.config') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-build-

    - name: Clone OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        curl -sSL https://raw.githubusercontent.com/chenmozhijin/turboacc/luci/add_turboacc.sh -o add_turboacc.sh && bash add_turboacc.sh
        cd $GITHUB_WORKSPACE/package
        git clone https://github.com/jerrykuku/luci-theme-argon.git

    - name: Configure .config
      run: |
        cd $GITHUB_WORKSPACE
        rm -rf .config
        cp .config.mine .config

    - name: Build OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        make -j$(nproc) V=s || \
        make V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-firmware
        path: |
          bin/targets/*
