name: Build OpenWRT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

    - name: Cache OpenWRT dl folder
      uses: actions/cache@v3
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('$GITHUB_WORKSPACE/feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-dl-

    - name: Cache OpenWRT build_dir
      uses: actions/cache@v3
      with:
        path: openwrt/build_dir
        key: ${{ runner.os }}-openwrt-build-${{ hashFiles('$GITHUB_WORKSPACE/.config') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-build-

    - name: Clone OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        make V=sc -j $(($(nproc)+1)) defconfig download clean world 

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-firmware
        path: |
          bin/targets/*
