name: Build OpenWRT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

    - name: Clone OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        cp .config .config  # 替换为你的实际配置文件路径
        make defconfig

    - name: Build OpenWRT
      run: |
        cd $GITHUB_WORKSPACE
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-firmware
        path: |
          bin/targets/*
